### PR TITLE
Add security and wrap in js module pattern

### PR DESCRIPTION
**Pull request by jscheel**
Remove default proxy for security, reveal korzConfig to window for user-defined router url, and wrap in simple js module definition. User must define router before making any cross-domain requests:

```
korzConfig.router = "http://example.org/";
```

I would also suggest not catching the errors and letting the browser actually throw real errors for debugging's sake.

### CODE REVIEW

**Comment by jpillora** [comment]
+1

**Comment by dahang** [comment]
I use Chrome get this error : Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

**Comment by odedgolan** [comment]
@dahang can you please elaborate what network call fails, its url and parameter. In addition, from which domain you invoke this call? 

Thanks!

**Comment by dahang** [comment]
OPTIONS http://korz.tomodo.me/http://dev.mydomain.com/rest/system/test Request header field Content-Type is not allowed by Access-Control-Allow-Headers. tomodo.korz-0.5.js:80 

XMLHttpRequest cannot load http://korz.tomodo.me/http://dev.mydomain.com/rest/system/test. Request header field Content-Type is not allowed by Access-Control-Allow-Headers. 50:1

From Chrome developer tools.

**Comment by yonatan-tomodo** [comment]
@dahang this is confirmed. an issue is opened I will be looked into.

**Comment by yonatan-tomodo** [comment]
Closing issue:
- wrap in simple js module written.
- default proxy is kept, for we want TOMODOkorz to work out of the box.

**Pull request closed without merging**
